auth    include password-auth
account include password-auth

can be autogenerated with authconfig-tui

ldap needs packages nss-pam-ldap

http://arstechnica.com/civis/viewtopic.php?f=16&t=1173082
    authconfig --enablekrb5 --enablemkhomedir  --enablepamaccess --enablelocauthorize --update
